### ISSUE TITLE
MSD: Wrong variables in config_overview.php

### ISSUE THREAD

**Issue by firefox747** [r23/MyOOS#10]
In MSDs config_overview.php, line 958 reads:

`	$aus['transfer2'].='<tr><td class="small">' . Help($lang['L_HELP_FTPSERVER'],"conf14",12) . $lang['L_FTP_SERVER'] . ':&nbsp;</td><td><input class="text" type="text" size="30" name="ftp_server[' . $i . ']" value="' . ( (isset($config['ftp_port'][$i])) ? $config['ftp_port'][$i] : "" )  . '"></td></tr>';`

It should read:
`
	$aus['transfer2'].='<tr><td class="small">' . Help($lang['L_HELP_FTPSERVER'],"conf14",12) . $lang['L_FTP_SERVER'] . ':&nbsp;</td><td><input class="text" type="text" size="30" name="ftp_server[' . $i . ']" value="' . ( (isset($config['ftp_server'][$i])) ? $config['ftp_server'][$i] : "" )  . '"></td></tr>';`

So ftp_server iso ftp_port.

Currently the port is saved as server.

**Comment by r23** [comment]
Thank you very much for pointing it out. I have eliminated the error.


https://github.com/r23/MyOOS/commit/c2ef9f8af8e65db4403ca7a95879604847205fcd
