### ISSUE TITLE
PHP 8 - Einstellungen lassen sich nicht speichern

### ISSUE THREAD

**Issue by rabe85** [r23/MyOOS#11]
Ich habe den Dumper lokal mit XAMPP 8.0.1 unter Windows 10 installiert. Die Einstellungen lassen sich dabei nicht speichern. Die Datei bleibt quasi leer.

**Comment by r23** [comment]
MSD in the current version https://github.com/r23/MyOOS/releases/tag/v2.4.17 saves under XAMPP Windwos 10

**Comment by rabe85** [comment]
Genau die Version habe ich, da passiert aber leider nichts.

**Comment by r23** [comment]
there are no known problems with Xampp, PHP 8.01 and Windows 10. It works in the development environment without any problems.
![grafik](https://user-images.githubusercontent.com/396063/107130137-0a932f80-68cb-11eb-9f6b-eac485ed61a8.png)

**Comment by rabe85** [comment]
Bei mir ist es noch v4.2.4-dev. 
Wenn ich Einstellungen speichern möchte werden die Warnungen vom Bild angezeigt und dass es gespeichert wurde. Stimmt aber nicht.
![2021-02-06 22 57 36 localhost 9da884976e5a](https://user-images.githubusercontent.com/8184353/107130580-30223800-68cf-11eb-82d0-6dd57c245d9f.png)

Beim Grundeinstellungen laden kommt "Array ( [0] => Array [1] => ( [2] => ) )".

**Comment by r23** [comment]
I have renewed the config and optimized the saving
https://github.com/r23/MyOOS/commit/553988aaca6d579d4637b1f92455eb9ab43ba466

I have removed the warnings
https://github.com/r23/MyOOS/commit/65b38284e830c2e9e54c04d897e93b88d425a9ac

we will publish a new version in a moment. Thanks for the hints
