### ISSUE TITLE
Website needs an update

### ISSUE THREAD

**Issue by Scanialady** [r23/MyOOS#2]
Please check your manual http://doku.oos-shop.de/myoos-benutzerhandbuch/ueber-myoos/eine-einfuehrung-in-das-myoos-shopsystem/ueber-phpbb/

You say in the forum, your software works with the current version of phpBB (3.2.5), which is included. Your manual talks about "modifications", which are abandoned since phpBB 3.1.0. Therefore, the information and the weblink are out of date, misleading for uninformed users. There are now "extensions" instead of "mods", and the product line phpBB 3.0.x has reached the "end of life"-state in 2015.

https://www.phpbb.de/community/viewtopic.php?f=9&t=233893

btw: nice product

**Comment by r23** [comment]
The myOOS Project uses mods and plugins and does not create mods. 

no support for phpb3 What is being developed or discontinued with the php BB3 - doesn't matter here
